global:
  scrape_interval: 5s
  evaluation_interval: 5s
  scrape_timeout: 4s

scrape_configs:
  - job_name: "bedrock-gateway-api-production"
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - "bedrock-gateway-alb-664380835.us-east-1.elb.amazonaws.com:80"
          - "backend.bedrock-gateway.local:8000"
          - "127.0.0.1:8000"
          - "host.docker.internal:8000"
        labels:
          environment: "production"
          service: "bedrock-gateway-backend"
          aws_region: "us-east-1"
          cluster: "bedrock-gateway-cluster-prod"


